### ISSUE TITLE
Cannot read property 'table_name' of undefined

### ISSUE THREAD

**Issue by jamespsterling** [zfcampus/zf-apigility-admin-ui#74]
When attempting to create a new service from conntected DB, 

TypeError: Cannot read property 'table_name' of undefined
    at a.e.ok (http://demoise.corp.york-claims.com:8888/apigility-ui/c22d22af.apigility.js:1:6663)
    at se.functionCall (http://demoise.corp.york-claims.com:8888/apigility-ui/6a8334db.vendor.js:6:18544)
    at jf.(anonymous function).compile.c.on.e (http://demoise.corp.york-claims.com:8888/apigility-ui/6a8334db.vendor.js:6:25923)
    at k.$get.k.$eval (http://demoise.corp.york-claims.com:8888/apigility-ui/6a8334db.vendor.js:5:14092)
    at k.$get.k.$apply (http://demoise.corp.york-claims.com:8888/apigility-ui/6a8334db.vendor.js:5:14370)
    at HTMLButtonElement.<anonymous> (http://demoise.corp.york-claims.com:8888/apigility-ui/6a8334db.vendor.js:6:25975)
    at HTMLButtonElement._.event.dispatch (http://demoise.corp.york-claims.com:8888/apigility-ui/6a8334db.vendor.js:2:14424)
    at HTMLButtonElement._.event.add.q.handle (http://demoise.corp.york-claims.com:8888/apigility-ui/6a8334db.vendor.js:2:11199)

**Comment by ezimuel** [comment]
@jamespsterling I fixed this issue with PR #75, I'm sorry for the inconvenient. Thanks for reporting!

**Comment by wesleywillians** [comment]
Is there any release with this hotfix?

**Comment by epoleacov** [comment]
How to apply this hotfix?

**Comment by wesleywillians** [comment]
You only need to add in your composer.json:
"zfcampus/zf-apigility-admin-ui": "dev-develop",

**Comment by jamespsterling** [comment]
I added this updated to composer.json and did an update. It's still generating the same javascript error. 

  - Updating zfcampus/zf-apigility-admin-ui (1.2.1 => dev-develop 94aea26)
    Checking out 94aea26214c4b065fc164e5f2bb39fe1f40ae33c

**Comment by PipStyles** [comment]
Still broken...

**Comment by MarceloHenriquee** [comment]
The same error happens to me, I've tried various forms found on the web but not yet paid off

**Comment by inobrega** [comment]
I made the same of @wesleywillians and it works like a charm ;)
A big hug to you, master. I'm your apprentice ;) @wesleywillians

**Comment by JunielKatarn** [comment]
@ilson-nobrega, @wesleywillians:
I'm unexperienced with Zend-Framework or Apigility.

Can you guys please detail a little more on how to apply the patch (specifically version 1.2.x)?
What section within composer.json should I edit?

**Comment by ilson-nobrega** [comment]
@JunielKatarn You just need to add "zfcampus/zf-apigility-admin-ui": "dev-develop" into your composer.json. It's so easy, look:

1. Just open composer.json file;
![image](https://cloud.githubusercontent.com/assets/7192737/11498753/930c9322-9808-11e5-8e2d-5b83fee1d8d4.png)

2. Now, search for "require-dev";
![image](https://cloud.githubusercontent.com/assets/7192737/11498771/b3d6b4fc-9808-11e5-9a39-c3c1a56eb48d.png)

3. Now just paste "zfcampus/zf-apigility-admin-ui": "dev-develop" within the braces ( {} ), like this:
![image](https://cloud.githubusercontent.com/assets/7192737/11498842/0cbc3c54-9809-11e5-8300-a30c55c47dfa.png)

4. Run php composer.phar install/update.

Rock 'n roll \m/

It's so easy.

Any questions, we are here.
See ya!

**Comment by aiamk** [comment]
@ilson-nobrega Thank you :)
